name: Catalogue

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

jobs:
  payment:
    name: Build and deploy catalogue microservice
    runs-on: ubuntu-latest  # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: NPM install
        run: npm install    

      # - name: Build the Docker image    
      #   run: docker buildx build --platform linux/arm64 -t ${{ secrets.ACR_NAME }}.azurecr.io/result-image:latest ./result
      - name: Login to the Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to the azure container registry
        run: az acr login --name ${{ secrets.ACR_NAME}}

      - name: Build and push Docker image
        run: docker buildx build --platform linux/arm64 -t ${{ secrets.ACR_NAME }}.azurecr.io/catalogue:latest --push ./catalogue
